### PR TITLE
Add Govee H5080 product

### PR DESCRIPTION
**Pull request by reydanro**
I've added the protocol documentation but also a set of python scripts that would help someone get started in working with a device like this.
This might not be standard for this repo, but it might be particularly useful for the pairing flow to have a working code example.

### CODE REVIEW

**Comment by reydanro** [comment]
bump @egold555

**Comment by egold555** [comment]
Somehow I missed this, thanks for the bump!

**Comment by egold555** [comment]
Apologies this took me so long. I've merged your code, and added a link to the readme.

I do like the python code you provided as a good example.

**Comment by reydanro** [comment]
Thanks @egold555, happy you thought the python was a good idea :)

**Pull request merged**
